kind: Service
apiVersion: v1
metadata:
  name: message-service
  labels:
    app: message-service
    visualize: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: message-service
