spring:
  application:
    name: ui
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: "1.0"
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST}
    port: 6379