kind: Service
apiVersion: v1
metadata:
  name: {{ include "guestbook.fullname" . }}-message
  labels:
    {{- include "base.labels" . | nindent 4 }}
    {{- include "message.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "message.selectorLabels" . | nindent 4 }}