apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guestbook.fullname" . }}-message
  labels:
    {{- include "base.labels" . | nindent 4 }}
    {{- include "message.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "message.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "message.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: message-service
        image: "{{ .Values.message.repository }}:{{ .Values.message.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.message.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
