apiVersion: v1
kind: Service
metadata: 
  name: {{ include "guestbook.fullname" . }}-mysql
  labels:
    {{- include "base.labels" . | nindent 4 }}
    {{- include "mysql.selectorLabels" . | nindent 4 }}
spec: 
  ports:
    # the port that this service should serve on
    - port: 3306
      protocol: TCP
  # label keys and values that must match in order to receive traffic for this service
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
