apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guestbook.fullname" . }}-ui
  labels:
    {{- include "base.labels" . | nindent 4 }}
    {{- include "ui.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: ui
        image: "{{ .Values.ui.repository }}:{{ .Values.ui.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.ui.pullPolicy }}
        env:
          - name: MESSAGE_HOST
            value: "http://{{ include "guestbook.fullname" . }}-message:{{ .Values.service.port }}"
          - name: GUESTBOOK_HOST
            value: "http://{{ include "guestbook.fullname" . }}-gb:{{ .Values.service.port }}"
          - name: REDIS_HOST
            value: {{ include "guestbook.fullname" . }}-redis
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
